# Generated by Django 4.2 on 2023-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_event_type_alter_event_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("typeless", "HIDDEN"),
                    ("media_artist", "MEDIA ARTIST"),
                    ("video_design", "VIDEO DESIGN"),
                    ("av_performance", "A/V PERFORMANCE"),
                    ("visuals", "VISUALS"),
                ],
                default="typeless",
                max_length=15,
                verbose_name="type of event",
            ),
        ),
    ]
